[package]
name = "tensor"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
evol = { path = "../../", version = "*" }
# evol = { path = "../../", version = "*", features = ["all"] }
