[package]
name = "tensor"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
kindle = { path = "../../", version = "*", features = [] }
