[package]
name = "tensor"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
firefly = { path = "../../", version = "*", features = ["all"] }
