[workspace]
resolver = "2"
members = [
	"crates/*",
	"examples/*",
]

[workspace.package]
edition = "2021"
version = "0.1.0"
readme = "README.md"
license = "MIT or Apache-2.0"

[package]
name = "firefly"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT or Apache-2.0"

[features]
default = []

all = ["nightly", "cuda"]

nightly = ["firefly-core/nightly"]
cuda = ["firefly-core/cuda"]

[dependencies.firefly-core]
path = "crates/firefly-core"
version = "0.1.0"

[workspace.dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = {version = "2.0.87", features = ["full"]}
trybuild = "1.0.101"
serde = {version = "1.0.215", features = ["derive"]}
candle-onnx = "0.8.0"

[dev-dependencies]
trybuild = "1.0.101"
